### ISSUE TITLE
iOS "unrecognized selector sent to instance" when setting GIDSignIn.sharedInstance().clientID

### ISSUE THREAD

**Issue by aventurella** [googlesamples/google-services#102]
In a Swift project, the following occurs:

In `application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool`

Setting 

```swift
GIDSignIn.sharedInstance().delegate = self
GIDSignIn.sharedInstance().clientID = "{{ my_client_id }}"
```
**OR**

```swift
GIDSignIn.sharedInstance().clientID = "{{ my_client_id }}"
GIDSignIn.sharedInstance().delegate = self
```

Causes a runtime error:

```
-[__NSDictionaryI gtm_httpArgumentsString]: unrecognized selector sent to instance
```

**Comment by aventurella** [comment]
I was able to get around this by updating the following Build Setting:

`Other Linker Flags: -ObjC`

And additionally linking `libz.tbd` to the project.

**Comment by ianbarber** [comment]
Ack, linker flag should be in the docs.

**Comment by ianbarber** [comment]
Doc updated, thanks!

**Comment by rlimberger** [comment]
I'm running into the same issue. I am trying to add Google sign in to a Swift 2.3 project in Xcode 8,building for iOS 10. i have manually added the Google Signin add and all the frameworks. I also added -ObjC as described in this issue, but am still getting the runtime error 

`-[__NSDictionaryI gtm_httpArgumentsString]: unrecognized selector sent to instance`

when calling

`GIDSignIn.sharedInstance().clientID = GOOGLE_CLIENT_ID`

**Comment by markcerqueira** [comment]
@rlimberger When I add the -ObjC flag I can't compile anymore. Mind sharing a screenshot or list of frameworks that you are linking with?

**Comment by fruxo-** [comment]
Hi there, same issue as rlimberger here.

`GIDSignIn.sharedInstance().clientID` = Resources.GOOGLE_CLIENT_ID`

produces:
`
2017-08-12 17:59:08.003 [81438:3069961] -[__NSDictionaryI gtm_httpArgumentsString]: unrecognized selector sent to instance 0x618000265040
2017-08-12 17:59:08.014 [81438:3069961] *** Terminating app due to uncaught exception ‘NSInvalidArgumentException’, reason: '-[__NSDictionaryI gtm_httpArgumentsString]: unrecognized selector sent to instance 0x618000265040'
`

I am not using any service apart from signing in. `GTLR` and `GTMSessionFetcher` have been imported as frameworks.

Any suggestion? 

Thanks,
Francesco

**Comment by jbolter** [comment]
I am all of the sudden running into this issue even though I haven't made any code changes that I'm aware of.  Still debugging but any ideas are welcome. We have -ObjC in the linker flags and the libz.tbd already in the project.

**Comment by yvdorofeev** [comment]
Anybody solved this? I'm getting the same issue. And I do have -ObjC flag...

**Comment by aleksey-ho** [comment]
I faced with the same issue, solved by adding pod 'GoogleSignIn' into my extention target. So make sure you don't forget to add it to your pods

**Comment by Minsoo-kim92** [comment]
Adding 'GoogleSignin' into pod is work for me
