### ISSUE TITLE
Register Android Device with GCM

### ISSUE THREAD

**Issue by pashtika** [googlesamples/google-services#11]
Please let me know how to register Android Device with Google Cloud Messaging (GCM) ? How can I get RegID?

**Comment by ingjuanocampo** [comment]
Hi, you must create you project on android developer console, 

https://developers.google.com/mobile/add?platform=android&cntapi=gcm&cnturl=https:%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fandroid%2Fclient&cntlbl=Continue%20Adding%20GCM%20Support&%3Fconfigured%3Dtrue

After that you have to create KEY SERVER for GMC,  then use the ID project to get you device token replacing the ID_SENDER on your java code, 

![image](https://cloud.githubusercontent.com/assets/11579887/8110664/e90b35e2-1033-11e5-809e-f9cd991c09cf.png)


change it for you Project ID,.

**Comment by kroikie** [comment]
Hi pashtika,

I'd start [here][1]. When you use InstanceID.getToken() you are registering your device with GCM. After that you need to sent the token you retrieved to your app server so that you can register with it. Then your app server can use the token to send messages to your device.

[1]: https://developers.google.com/cloud-messaging/android/start
