### ISSUE TITLE
subscribe to Topics

### ISSUE THREAD

**Issue by yoav2** [googlesamples/google-services#118]
* The app subscribe to the same topics every time it starts(onCreate) Isn't a problem? 

* There is no unsubscribe call in the code. is unsubscribe from a topic happen automatic when uninstalling an app?

**Comment by kroikie** [comment]
Subscribing multiple times is not a problem since only the initial subscription goes to the server, subsequent subscribe calls are handled locally. 

Google Play Services will attempt to unsubscribe the topic on uninstall on Android. However once the app is uninstalled the registration token will eventually be invalid and thus any attempt to send messages to that token will fail, even from the topic servers.

**Comment by yoav2** [comment]
If I have 100,000 users and every user is subscribe to 10 topics, is that mean I got to the 1 million subscription limitation? or I only have 100,000 subscription?

**Comment by kroikie** [comment]
Yes you would hit the current limit, the limit only looks at the number of subscriptions, now users.
