### ISSUE TITLE
GoogleAppIndexing: Bitcode Support (again)

### ISSUE THREAD

**Issue by grizzly** [googlesamples/google-services#198]
Hi, Issue #95 was closed, you said full Bitcode support was added to AppIndexing (iOS). But we still get the bitcode error at the linker:

ld: bitcode bundle could not be generated because '...../Pods/GoogleAppIndexing/Frameworks/GoogleAppIndexing.framework/GoogleAppIndexing(GSDDeepLink.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

So it seems that this issue is still open?

Thx
Stefan

**Comment by ianbarber** [comment]
Reopened.

**Comment by adamjack** [comment]
Cocoapods installs:

      Installing GoogleAppIndexing (2.0.3)

but then I get this:

ld: bitcode bundle could not be generated because '/Users/adamjack/Work/BigOven/iOS/BigOven/Pods/GoogleAppIndexing/Frameworks/GoogleAppIndexing.framework/GoogleAppIndexing(GSDDeepLink.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this problem resolved, or not? Is it just not resolved for the Cocoapods release?

**Comment by jmkk** [comment]
Bitcode is not there in 2.0.3 - @ianbarber why was this issue closed? Thanks.
