### ISSUE TITLE
Not working in the  targetSdkVersion more than 22 i.e 23, 24, 25

### ISSUE THREAD

**Issue by sudarshanthite** [googlesamples/google-services#320]
### Step 1:  environment

  * Device: __Motorola___
  * OS version: __Marshmallo___
  * SDK version: __23___
  * [Android] Google Play Services version: _com.google.android.gms:play-services-auth:8.3.0____
  
### Step 2:  problem:
Not working in the android API version 23, 24 getting the response code 0 in the onActivityResult()
provide by you and getting the exception
java.lang.SecurityException: Missing android.permission.GET_ACCOUNTS

#### Steps to reproduce:
Just set the targetSdkVersion more than 22 and run this demo provide by you it dosent work
  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * Login has to work and user details has to show.
  

  ```

**Comment by samtstern** [comment]
@sudarshanthite it sounds like you need to request the `GET_ACCOUNTS` permission at runtime.  Runtime permissions were introduced in API level 23, so that's why it's not working for you.

Documentation:
https://developer.android.com/training/permissions/requesting.html

If you want a library to help you:
https://github.com/googlesamples/easypermissions

I am going to close this issue since it is not relevant to the code in this repository.
