### ISSUE TITLE
How to disable FCM for one of the flavours

### ISSUE THREAD

**Issue by kaa-awem** [googlesamples/google-services#361]
Hi.

  we are building both Google Play and other non-Google-play build using the same gradle build script. We want to disable FCM for non-GP builds, however, apply plugin: 'com.google.gms.google-services' adds GP-specific data and permissions.

  Is the an official way to disable FCM for certain build flavors without if-based trickery?

**Comment by samtstern** [comment]
@kaa-awem that's a good question!  Since this is a non-standard use case I would recommend not using the `google-services` gradle plugin at all.  This guide can help you learn how it works and therefore how to go without it:
https://developers.google.com/android/guides/google-services-plugin

Basically the plugin does two things:

1. Make sure you have some minimal dependencies
2. Convert a `json` file into `xml` strings

Since you don't need (1), all you need to do is reproduce (2) by yourself. That just means reading the `json` file and creating the proper strings in each flavor of your app.
