### ISSUE TITLE
GoogleSignIn.getLastSignedInAccount returns account even if the user has removed it

### ISSUE THREAD

**Issue by UgVaDevLabs** [googlesamples/google-services#410]
* Device: Any
  * OS version: Any
  * SDK version: Any
  * [Android] Google Play Services version: 16.0.91
  
GoogleSignIn.getLastSignedInAccount returns account even if the user has explicitly removed it via device settings.

#### Steps to reproduce:

  1. Sign in to the application via google
  2. Explicitly remove the signed in account from settings
  3. GoogleSignIn.getLastSignedInAccount(this) returns account but it should return null
  
#### Expected Results:

  GoogleSignIn.getLastSignedInAccount(this) should return null if account was removed by the user

**Comment by samtstern** [comment]
@UgVaDevLabs that's an interesting edge case, thanks for reporting it!  I will file a bug internally.

**Comment by UgVaDevLabs** [comment]
Any progress on this issue?

**Comment by davidsun** [comment]
It is expected that GoogleSignIn.getLastSignedInAccount() can return an account that is not on the device. The reason is that getLastSignedInAccount() logic lives in Google sign-in SDK which is part of the third party app. The third party app, in theory, should not have the permission to access account data. So it is infeasible for getLastSignedInAccount() to guarantee that it only returns the account that is on the device.

**Comment by samtstern** [comment]
Thanks @davidsun!

**Comment by UgVaDevLabs** [comment]
How do you then suggest implementing token revocation defined in your documentation?https://developers.google.com/identity/sign-in/android/v1/disconnect. "If the user deletes their account, you must delete the information that your app obtained from the Google APIs."
