### ISSUE TITLE
gcm not send to apn when iOS app was killed.

### ISSUE THREAD

**Issue by kim-seung-hwan** [googlesamples/google-services#60]
gcm send to apn when foreground and background.  <- send ok
but, Force Quit Application, gcm not send to apn.          <- send not ok

when Force Quit Application, apn is possible send notification because, "APN Tester" is send notification Available.

< test condition >
iPhone 4
7.1.2
object c code(GcmExample.app)
use curl
< curl --header "Authorization: key=$server_api_key" \
--header Content-Type:"application/json" \
https://android.googleapis.com/gcm/send \
-d "{\"data\":{\"title\":\"title\"},\"notification\":{\"body\":\"noti test\",\"content_available\":true},\"to\":\"$token\"}" >
"GcmServerDemo" tool
"APN Tester" tool

**Comment by silvolu** [comment]
@kim-seung-hwan just to make sure, is this the APN Tester tool that you're using:
https://itunes.apple.com/us/app/apn-tester-free/id626590577

**Comment by kim-seung-hwan** [comment]
@silvolu 
yes, i use this.

**Comment by negedzuregal** [comment]
having the same problem exactly

**Comment by silvolu** [comment]
@kim-seung-hwan if I understand correctly this is working when you use the APN Tester tool? What is the content of the payload that you are sending with the APN Tester tool?

**Comment by promactkaran** [comment]
referencing to https://github.com/googlesamples/google-services/issues/67

**Comment by InViZz** [comment]
had the same problem.
fix it by adding "priority": "high" to push message:
{
  "registration_ids": ["nYG2y3HGY3...TSR-i3KWNqI"],
  "notification": {
    "title": "Hello, world!",
    "body": "a",
    "badge": 3,
    "sound": "default"
  },
	"priority": "high"
}

**Comment by silvolu** [comment]
Thanks @InViZz! That makes sense, a couple of weeks ago we changed the default priority of the messages to normal, and it looks like Apple does not deliver immediately 'normal' messages to apps that have been swiped out. Please don't just use high priority to make sure that your notifications are delivered immediately unless the message is time-critical, because that will have an impact on the battery life of your users; check our guide on [setting the value of priority](https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message).

**Comment by kim-seung-hwan** [comment]
thanks!
